blank_issues_enabled: false
contact_links:
  - name: ğŸ‡°ğŸ‡· ì´ìŠˆ ìœ í˜• ì„ íƒ
    url: https://github.com/username/repo-name/issues/new/choose
    about: ì ì ˆí•œ ì´ìŠˆ ìœ í˜•ì´ ì•„ë‹ˆë¼ë©´ ë‹¤ë¥¸ ìœ í˜•ì„ ì„ íƒí•´ì£¼ì„¸ìš”.
